### ISSUE TITLE
Bootstrap and React Dependencies prevent usage with other tools

### ISSUE THREAD

**Issue by dantrevino** [universelabs/meta#33]
@vuejs is a popular and growing framework, and not everyone is using Bootstrap.  Removing these as dependencies would allow a wider range of developers to implement meta.

**Comment by guylepage3** [comment]
@dantrevino, I played around with Meta, Vue and removal of "Bootstrap" over the weekend and discovered that Meta works well without Bootstrap. And since Meta is only a `.scss` file, one is able to install Meta within any JS library that they'd like. You just need to import the `meta.scss` file after running...

```
npm i @universelabs/meta
```

Let me know if you have any issues.. Also, Meta now has a new Color System and after today it will have an updated Typography System to support two types of typography;
  1. GUI typography
  2. Editorial typography

**Comment by guylepage3** [comment]
Closing this issue.
